### ISSUE TITLE
Release 3.0 Checklist 

### ISSUE THREAD

**Issue by awilcoxa** [magento-research/pwa-studio#1239]
Issue to track all activity for PWA 3.0 Release. (Based off activities on #923)

### Core Bugs Blocking Full Regression
- [x] [MC-16644](https://jira.corp.magento.com/browse/MC-16644) [2.3.2 REGRESSION] Configurable Product Result w/ UrlKey Filter
- [x] [MC-16651](https://jira.corp.magento.com/browse/MC-16651) ElasticSearch6 Dependency Won't Install
- [x] [MC-17050](https://jira.corp.magento.com/browse/MC-17050) ElasticSearch6 Broken w/ Boolean Attribute
  - We can get around this bug by deleting the `has_video` attribute from the sample data; not used by Venia, so not a big deal.

### Current Action Items
- [ ] Ensure all items for release are identified and tagged @awilcoxa @cherdman 
- [x] Create `release/3.0` from commit prior to Imagine work - @tjwiebell 

### RTM
- [x] Author & Merge Release Notes to ./changelog.md : @jcalcaben @dpatil-magento 
- [x] Commit Release Notes: @jcalcaben @zetlen @jimbo
- [x]   Approve/signoff build: @zetlen @jimbo @dpatil-magento
- [x]   Deploy to now.sh: @zetlen
- [x]   Verify now.sh deploys & scale configuration: @zetlen
- [x]   Deploy to Magento Cloud: @bbatsche @tjwiebell @dpatil-magento 
- [x]   Verify Cloud deploys: @bbatsche @tjwiebell @dpatil-magento  and any Cloud ops personnel

### GA
- [ ]   In Github, create pre-release 3.0.0: @zetlen @jimbo
- [ ]   Push the release tag to the repo
- [ ]   Merge release 2.1.0 to master
- [ ]   Copy CHANGELOG to Github release details : @zetlen @jimbo
- [ ]   Publish devdocs: @jcalcaben
- [ ]   Publish to NPM/package managers: @zetlen
- [ ]   Rebase all outstanding PRs on develop @sirugh

**Comment by awilcoxa** [comment]
Need to review release activities listed above.

**Comment by cherdman** [comment]
Closing this issue since we're done with RTM. Creating a [new issue](https://github.com/magento-research/pwa-studio/issues/1343) to track GA activities prior to release.
