### ISSUE TITLE
Release Checklist 3.0.0 - GA

### ISSUE THREAD

**Issue by cherdman** [magento-research/pwa-studio#1343]
### GA
- [ ]   In Github, create pre-release 3.0.0: @zetlen @jimbo
- [ ]   Push the release tag to the repo
- [ ]   Merge release 3.0.0 to master
- [ ]   Copy CHANGELOG to Github release details : @zetlen @jimbo
- [ ]   Publish devdocs: @jcalcaben
- [ ]   Publish to NPM/package managers: @zetlen
- [ ]   Rebase all outstanding PRs on develop @sirugh
