### ISSUE TITLE
Implement middle-tier reference architecture

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#180]
## Description

As a developer I want a platform agnostic approach to creating and deploying PWA storefronts. Builds upon research spike on middle-tier specification.

- Implement development mode with middle-tier
- Minor refactoring of buildpack and Venia (as appropriate)
- Minor refactoring of Magento 2 inegration points
- Supporting documentation (updates)

## Expected result:

Summary of findings
Internal and external review
Additional user stories or scenarios (as appropriate)

## Tasks

- [x] Publish first draft of UPWARD whitepaper
- [ ] Complete draft of UPWARD reference API
- [ ] Write UPWARD server test harness
- [ ] Write JS reference implementation
- [ ] Stretch: Integrate into webpack-dev-server as middleware

**Comment by ericerway** [comment]
Kamino cloned this issue to [magento-research/pwa-studio](https://github.com/magento-research/pwa-studio/issues/258)

**Comment by ericerway** [comment]
Partially complete, remaining tasks moved to #258 in next sprint. 
- [ ] Write UPWARD server test harness
- [ ] Write JS reference implementation
- [ ] Stretch: Integrate into webpack-dev-server as middleware
