### ISSUE TITLE
 Navigation experience for Venia

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#240]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[X] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## Description

https://magento-research.github.io/pwa-studio/venia-pwa-concept/component/product-listing/

![image.png](https://images.zenhubusercontent.com/5a71f21a4b5806bc2bc51012/9b18943a-36a3-4cee-883a-d2751f2a129b)

As a shopper I want to browse the Venia store from a prominent location on the storefront with access to categories and Account from all locations so that I can make a purchase.

Considerations should include primary, secondary and tertiary levels with inline actions to return to the top level in the menu and an option to close the menu altogether from view.

#### Assumptions
- Working routing and product catalog in Magento 2 via GraphQL/REST
- Category tree GraphQL query needed

## Tasks

- [ ] Update current navigation in Venia based on latest UX design/proto
- [ ] Addition of special visual treatment for featured categories (e.g. Sale and Clearance)
- [ ] Utilize product/catalog data to retrieve categories and links
- [ ] Placeholder link for Account until Authentication story is ready

**Comment by ericerway** [comment]
Kamino cloned this issue to [magento-research/pwa-studio](https://github.com/magento-research/pwa-studio/issues/271)
