### ISSUE TITLE
Shipping methods for Venia

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#241]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[X] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## Description

![image.png](https://images.zenhubusercontent.com/5a71f21a4b5806bc2bc51012/ae322569-da2c-42d5-ae8a-0df107984e32)

As a shopper, I want to choose a shipping method when making a "Get it By" purchase on Venia so that I can understand any tradeoffs with time and cost in my checkout experience.

(default options from Magento 2; these will be pulled from config)
- Flat Rate (Fixed) at $25 USD
- Best Way (Table Rate) at $5 USD

#### Assumptions
- Fixed shipping methods for MVP; options from Magento 2 configuration
- Leveraged address work from Venia including form fields, other aspects
- Updated Order Summary (with pricing)
- Date not included in MVP

## Tasks
- [ ] Review Payment API requirements/needs (useful data)
- [ ] Update shipping in Venia to allow for shopper/user selection
- [ ] Verify update in pricing to cart and checkout
