### ISSUE TITLE
Payment methods for Venia (Check and Money Order)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#242]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[X] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## Description

![image.png](https://images.zenhubusercontent.com/5a71f21a4b5806bc2bc51012/f7f4cd74-4074-4230-85b1-b3db5fcedbbe)

As a shopper, I want to select from several payment options ("Pay With") in checkout including check/money order and other methods (future) so that I can pay for my purchase.

Check / Money order will be default option for MVP (Magento 2.X)
Future consideration for Magento Payments, Paypal Express and others

#### Assumptions
- Payment methods taken from Magento 2 configuration (e.g. check, money order)
- Basic payment *only* not seen in mock/concept; static methods only
- Payment Request API handled separately (concept)

## Tasks
- [ ] Discovery to retrieve payment methods from API
- [ ] Update Pay With options in Checkout to allow for selection
- [ ] Testing and documentation (as appropriate)

**Comment by ericerway** [comment]
Kamino cloned this issue to [magento-research/pwa-studio](https://github.com/magento-research/pwa-studio/issues/475)
