### ISSUE TITLE
Implement basic login for Venia (MVP)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#249]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## Description

![image.png](https://images.zenhubusercontent.com/5a71f21a4b5806bc2bc51012/ddab2572-d735-4309-a4ec-3f6ace2227c4)

As a shopper, I want to login to the Venia storefront using my email and password (previously created) so that I can access previous orders, subscriptions and other features of my account.

- Email (required)
- Password (required)

#### Assumptions
- Usage of existing account (e.g. Veronica Costello) 
- Basic error messaging OK as placeholder until Account epic story complete
- Forgot password (future)
- Create an account (future)
- Edits and validations (future)

## Tasks
- [ ] Discovery to retrieve and verify email/password from API
- [ ] Display basic error messaging (from API; account disabled, user/pass incorrect)
- [ ] Testing and documentation (as appropriate)

**Comment by ericerway** [comment]
Kamino cloned this issue to [magento-research/pwa-studio](https://github.com/magento-research/pwa-studio/issues/250)

**Comment by soumya-ashok** [comment]
Please review:
![my account - create account](https://user-images.githubusercontent.com/25960021/44755452-de650900-aaeb-11e8-851b-048259f8657d.jpg)
