### ISSUE TITLE
Design account recovery for Venia (MVP)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#253]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## Description

As a shopper, I want to recover my account information from Venia in the event that I have forgotten my password. 

- Email (required)
- Error messaging (Global Styles)

#### Assumptions
- [ ] Considerations for base case but options for captcha (TBD) and reset in the future
- [ ] Offline needs including email design and layout

## Tasks
- [ ] Discovery for LUMA in how it handles account recovery for M2
- [ ] Design artifacts with proposed solution (including revisions)
- [ ] Review and documentation (as appropriate)

**Comment by soumya-ashok** [comment]
I have the draft of the layouts for both create account and sign in. Need a bit more definition around the recovery path before mocks are built / refined.

**Comment by ericerway** [comment]
Kamino cloned this issue to [magento-research/pwa-studio](https://github.com/magento-research/pwa-studio/issues/255)

**Comment by ericerway** [comment]
Kamino cloned this issue to [magento-research/pwa-studio](https://github.com/magento-research/pwa-studio/issues/270)

**Comment by ericerway** [comment]
Splitting CATCHA and outstanding questions into Sprint 25, marking rest as complete/closed. Thanks!
