### ISSUE TITLE
Design for editing shopping cart (mini) with Venia

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#255]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## Description

As a shopper, I want to make changes (edit) my shopping cart in Venia so that I can make a better purchase decision.

- Remove/delete items from cart
- Update quantities in cart (by item) 

#### Assumptions
- [ ] Considerations mini-cart and checkout
- [ ] Future consideration (adaptability) for full size cart and checkout
- [ ] Existing functionality from LUMA with Venia presentation and PWA characteristics

## Tasks
- [ ] Design artifacts with proposed solution (including revisions)
- [ ] Review and documentation (as appropriate)
