### ISSUE TITLE
Update pwa-studio homepage for community and recognition

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#263]
## This issue is for the following packages:

[ ] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[X] `pwa-devdocs`

## Description

As a developer I want to quickly understand the requirements, installation and contribution needs of PWA Studio so that I can start using it and help contribute immediately. In addition, PWA Studio should be consistent with other efforts including GraphQL, MSI and others.

- Contribution and Community Maintainers
- Top Contributors
- Labels (definitions)
- Reporting issues
- Licensing

Example: https://github.com/magento/graphql-ce

#### Assumptions
- Existing homepage from Magento Research
- Consideration of unique PWA scenarios 

## Tasks
- [ ] Review of GraphQL, MSI and other projects to determine gaps
- [ ] Updated content on /pwa-studio homepage
- [ ] Feedback (as appropriate)
