### ISSUE TITLE
Implement basic Search results for Venia (PWA)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#264]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[X] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## Description

(link from Invision to Search results; related to pagination)

As a shopper, I want to search for products on the Venia storefront using basic keywords (e.g. hoodie) so that I can make an informed purchase.

- Updates to Venia header (search functionality)
- Search initiated by keyboard (e.g. Return to commit)

#### Assumptions
- Filtering, sorting not part of this first effort (MVP)
- Pagination and autocomplete to be considered in future (component?)
- Utilize REST API as GraphQL is in development; GraphQL preferred

## Tasks
- [ ] Discovery to retrieve product catalog data from REST or GraphQL** (products)
- [ ] Identify future considerations (tasks) for filtering, pagination and other experiences
- [ ] Implement basic search and search results page(s)
- [ ] Testing and documentation (as appropriate)

**Comment by ericerway** [comment]
Kamino cloned this issue to [magento-research/pwa-studio](https://github.com/magento-research/pwa-studio/issues/265)

**Comment by ericerway** [comment]
Kamino cloned this issue to [magento-research/pwa-studio](https://github.com/magento-research/pwa-studio/issues/267)

**Comment by ericerway** [comment]
Kamino cloned this issue to [magento-research/pwa-studio](https://github.com/magento-research/pwa-studio/issues/294)

**Comment by ericerway** [comment]
Kamino cloned this issue to [magento-research/pwa-studio](https://github.com/magento-research/pwa-studio/issues/313)

**Comment by ericerway** [comment]
Talked to Bargreen, this PR should come in next week with Sprint 28. Thanks! 🎉

**Comment by ericerway** [comment]
Talked to Bargreen, this PR should come in next week with Sprint 28. Thanks! 🎉

**Comment by supernova-at** [comment]
Closed by #639.
