### ISSUE TITLE
Implement editing for Venia mini shopping cart (MVP)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#265]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[X] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## Description

![image](https://user-images.githubusercontent.com/2686596/45183975-320ddb80-b1eb-11e8-9a99-579b17aa6414.png)

As a shopper, I want to edit, remove and add a Venia item to favorites from Checkout so that I can make an accurate purchase online.

- Updates to shopping cart (mini)
- Ability to Add to Favorites, Edit item, Remove item  

#### Assumptions
- Thumbnails and product/item details may be considered in future iteration
- Subtotal and items should update with any changes

## Tasks
- [ ] Discovery to understand how shopping cart is implemented
- [ ] Determine feasibility of ATF
- [ ] Implement basic edit, remove and add to favorites
- [ ] Implement thumbnail and basic product data (title, details per UX)
- [ ] Testing and documentation (as appropriate)
