### ISSUE TITLE
Implement updated Order Confirmation for Venia (PWA)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#267]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## Description

Mockup for order confirmation page - https://magento.invisionapp.com/share/WQN5F7BYBPG#/screens/324379326

![image](https://user-images.githubusercontent.com/2686596/47090801-39aca100-d1e9-11e8-907d-19352f305732.png)

As a shopper, I want to have immediate access to the order that I placed on Venia after checkout so that I can check the status at any time.

#### Assumptions
- Completed MVP for Checkout of Venia
- REST/GraphQL coverage to retrieve order information (e.g. ID#, email)
- Password delivered via email upon Create Account based on order information (changed)
- Detailed account creation per UX prototype will be handled in future sprint
- Back button is not necessary as part of the left drawer but close is required [NEW]

## Tasks
- [ ] Discovery for REST/GraphQL coverage with orders and mail (service)
- [ ] Identify admin-only endpoints with data customer would want to see, for future adaptation
- [ ] Expose \Magento\Sales\Api\OrderCustomerManagementInterface::create in REST API
- [ ] Implement UI as React RootComponent displaying order data from REST API
- [ ] Implement UI interaction (button) to invoke API call that sends account creation email
- [ ] Testing and documentation (as appropriate)

**Comment by ericerway** [comment]
Kamino cloned this issue to [magento-research/pwa-studio](https://github.com/magento-research/pwa-studio/issues/278)

**Comment by dmtrkad** [comment]
- [ ]   Checkout review  
(1 SP)  
- [ ]   Discovery for REST/GraphQL coverage with orders and mail (service)
         1.  Need details 
- [ ]   Identify admin-only endpoints with data customer would want to see, for future adaptation
         1. Need details . Difference between user&admin roles 
- [ ]   Expose \Magento\Sales\Api\OrderCustomerManagementInterface::create in REST API
         1. Need details
- [ ]   Implement UI page container 
(1 SP)
- [ ]   Fetching Order information on page load event 
(1 SP)
- [ ]   Implement UI interaction (button) to invoke API call that sends account creation email
(1 SP)
- [ ]   Adding unit tests
(1.5 SP) 
- [ ]   Adding testing scenarios 
        1. Need details which will be used for such needs
- [ ]  Testing and documentation (as appropriate)
        1. Need details. What kind of docs need to be updated ? JS doc? Tech doc? Test doc? 

**Q&A**
1. Do we need to support mobile versions only? No desktop
2.  What're the integration details for REST/GraphQL coverage structure? (Api endpoints exists: Order information, sending an email ). What's the behavior if the user clicks "continue shopping"-button 2. What's happened when the user taps on a "Create an account"-button in case if an email 's sent (Positive&Negative scenario)
3. What kind of endpoints need to be provided for an admin role? 
4. What kind of data do we need to display to customers in terms of admin-only endpoints ?
5. Business requirements are needed to resolve \Magento\Sales\Api\OrderCustomerManagementInterface::create in REST API

**Comment by ericerway** [comment]
- This needs to support mobile and desktop
- Need @zetlen on the REST/GraphQL - we typically fall back to REST where GraphQL is not available
- Need @zetlen on the endpoints/data/resolve as well

**Comment by dmtrkad** [comment]
> * This needs to support mobile and desktop
> * Need @zetlen on the REST/GraphQL - we typically revert to REST where GraphQL is not available
> * Need @zetlen on the endpoints/data/resolve as well

@ericerway let you please kindly use an approach to update answers under questions to make things clean. I've moved one of your answer under the question and updated my comment ahead

**Comment by Starotitorov** [comment]
Tasks:
[] Implement page component.
[] Review checkout flow.
[] Implement fetching order information.
[] Add button to invoke API call that sends account creation email.
[] Add unit tests.
[] Add docs.

**Comment by ericerway** [comment]
Kamino cloned this issue to [magento-research/pwa-studio](https://github.com/magento-research/pwa-studio/issues/362)

**Comment by vitalics** [comment]
Scenario ready for review and available from link below
https://app.hiptest.com/l/sc/2337958

**Comment by zetlen** [comment]
I've learned from our architects that we have no REST API endpoint for displaying order confirmation data for guest checkouts. In fact, even in Luma, the guest checkout confirmation page is very sparse:

![image](https://user-images.githubusercontent.com/1643758/47241581-dcb01700-d3b1-11e8-94c2-cdaa06eeada2.png)

@eerway @Starotitorov @soumya-ashok For MVP, let's reduce the scope of the confirmation page for guest checkouts to show just what the Luma guest confirmation page shows.

**Comment by Starotitorov** [comment]
@ericerway @zetlen @soumya-ashok Guys, everything is Ok with the scope. I was able to get required information to render it on the page, now we are rendering almost the same data on our page. @zetlen, it was just a question, i noticed this, and it seemed strange to me, that I was able to submit an order for guest user, but could not fetch order details using /orders/{orderId} endpoint.

**Comment by dmtrkad** [comment]
https://github.com/magento-research/pwa-studio/pull/401
Fixing of review comments will be finished Oct, 24

**Comment by Starotitorov** [comment]
@ericerway, @awilcoxa, @zetlen, we are blocked by discussion related to grouping application by features and review of https://github.com/magento-research/pwa-studio/pull/401

**Comment by Starotitorov** [comment]
There is an issue with running CI jobs for https://github.com/magento-research/pwa-studio/pull/505. This issue blocks merging of the pull request. @zetlen, I need you help, I can run all test, lint, prettier, builds scripts locally, but CI jobs fail.
