### ISSUE TITLE
Design account recovery for Venia (MVP)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#270]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## Description

As a shopper, I want to recover my account information from Venia in the event that I have forgotten my password including CAPTCHA. 

- Email (required)
- Error messaging (Global Styles)
+ CAPTCHA (review for PWA and Accessibility need)

#### Assumptions
- [ ] Considerations for base case but options for captcha (TBD) and reset in the future
- [ ] Offline needs including email design and layout
- [ ] Determination of state/location in Venia shopping experience

## Tasks
- [ ] Design artifacts with proposed solution (including revisions)
- [ ] Review and documentation (as appropriate)

**Comment by ericerway** [comment]
Kamino cloned this issue to [magento-research/pwa-studio](https://github.com/magento-research/pwa-studio/issues/275)

**Comment by ericerway** [comment]
Kamino cloned this issue to [magento-research/pwa-studio](https://github.com/magento-research/pwa-studio/issues/295)

**Comment by ericerway** [comment]
CAPTCHA will be deferred to a future sprint.
