### ISSUE TITLE
Orders experience design updates for Venia (MVP)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#275]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## Description

As a shopper, I want to find and view the details of previous orders placed on Venia so that confirm accuracy or reorder in the future.

- Order status (e.g. PENDING)
- Product name
- SKU
- Price
- Quantity
- Subtotal (S&H and Grand Total)
- Order information (shipping address/method, billing address, payment method)
- My Orders listing (order#, date, ship to, order total, status and action(s))

#### Assumptions
- [ ] Fixed limit of My Orders shown; X per page (pagination component)
- [ ] Ability to reorder based on the order details (one click)
- [ ] Ability to print order details (print friendly)

## Tasks
- [ ] Update Venia prototytpe to account for new assumptions and details
- [ ] Review and documentation (as appropriate)
