### ISSUE TITLE
Implement Product Option Selector Presentation UI for Venia

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#278]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## Description

![image](https://user-images.githubusercontent.com/2686596/45492048-e8644a00-b730-11e8-8c7e-40f42c6242f9.png)

As a shopper, I want to choose a configurable product (colors, sizes) on Venia so that I can make an informed purchase.

### Acceptance Criteria
 - Venia prototype selectors are implemented from mock
 - Components accept props for internal display state and provide hooks for event listeners
 - Storybook stories implemented for demonstration
 - Storybook states exist for selected, out of stock, and metadata display
 - Test coverage exists

#### Assumptions
- Completed MVP for Checkout of Venia working on local
- REST/GraphQL coverage to retrieve sample product data (configurable examples)

## Tasks
- [ ] Evaluation of Option Selector prototypes that do exist for code reuse
- [ ] Implementation of presentation components (receiving props, not binding to API data) that implement Venia option selector UI
  - [ ] Numeric value selector (e.g. Size)
  - [ ] Color swatches
  - [ ] Text values
  - [ ] All options: Show out-of-stock indicator
- [ ] Testing and documentation (as appropriate)

**Comment by ericerway** [comment]
Kamino cloned this issue to [magento-research/pwa-studio](https://github.com/magento-research/pwa-studio/issues/279)
