### ISSUE TITLE
Implement pagination for Category on Venia (PWA)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#279]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## Description

WIP: (Design not final)
![image](https://user-images.githubusercontent.com/2686596/45491861-607e4000-b730-11e8-9f1c-f057ffdaecec.png)

As a shopper, I want to browse multiple pages of products from Venia so that I can make an informed purchase.

Scenarios include: first page, last page, middle page, only one page, too many pages to count (start/end/middle)

#### Assumptions
- Utilize pagination component from Venia (prototype)
- Completed MVP for Checkout of Venia working on local
- REST/GraphQL coverage to retrieve sample product data (configurable examples)

## Tasks
- [ ] Discovery to retrieve product data from REST or GraphQL (preferable)
- [ ] Implement pagination component (styled) on Category
- [ ] Testing and documentation (as appropriate)
- [ ] Storybook implementation for all states
