### ISSUE TITLE
Venia user research and validation planning with UX

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#280]
## This issue is for the following packages:

[ ] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## Description

Additional research is needed to validate the recent updates to PWA Studio and Venia as part of an iterative approach to design. This will be based on work from recent "headless" implementations (developer) and traditional mobile shopping (shoppers) behaviors using a prototype.

#### Assumptions
- Available participants for informal studies; both developers and shoppers
- Methodology and details will be determined by UX with feedback from team

## Tasks
- [ ] High level research plan for both developer and shopper-led studies
- [ ] Recruiting for developer (Austin) and shopper (friends&family)
- [ ] Execute interviews and user research with team
- [ ] Summary of findings; high level findings and detailed report (as appropriate)

**Comment by ericerway** [comment]
Refocused story on research planning (breaking into multiple) for Sprint 27. Thanks!

**Comment by awilcoxa** [comment]
Closing this story as we'll re-evaluate UX research efforts in upcoming FY19 planning. New stories will be created pending outcome of those planning activities.
