### ISSUE TITLE
Add support for Configurable Products and option selection to Venia

### ISSUE THREAD

**Issue by zetlen** [magento-research/pwa-studio#283]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[x] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## Description

![image](https://user-images.githubusercontent.com/2686596/45492048-e8644a00-b730-11e8-8c7e-40f42c6242f9.png)

As a shopper, I want to choose a configurable product (colors, sizes) on Venia so that I can make an informed purchase.

### Acceptance Criteria
 - Configurable products configuration options
 - Components accept props for internal display state and provide hooks for event listeners
 - Storybook stories implemented for demonstration
 - Storybook states exist for selected, out of stock, and metadata display
 - Test coverage exists

#### Assumptions
- Completed MVP for Checkout of Venia working on local
- REST/GraphQL coverage to retrieve sample product data (configurable examples)

## Tasks
- [ ] Enhance GraphQL API calls to include option information
- [ ] Enhance REST API calls to Cart to include option selection
- [ ] Create state management modules (actions, reducers) for product configuration state and integrate
- [ ] Create container components which bind to API data and action creators
- [ ] Integration Option selector presentation components from #278 into containers
- [ ] Integrate containers into Product Detail page
- [ ] Testing and documentation (as appropriate)

**Comment by zetlen** [comment]
Feel free to add Storybook to Venia for the purposes of the story! All dev deps without CLI commands (or annoying peer dependencies) have been pulled to the repo root `package.json` as of #223. So you could install `@storybook/react` in Venia and get it going pretty easily.
