### ISSUE TITLE
Discovery for Vagrant environment for PWA [SPIKE]

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#312]
## This issue is for the following packages:

[ ] `venia-concept`
[X] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[X] `pwa-devdocs`

## Description

As a developer, I want to utilize Vagrant to quickly get started with development for PWA Studio regardless of my environment and potentially contribute to the project.

#### Assumptions
- Vagrant is a preferred option vs. Docker (reliability and maintenance)
- Environment will always keep the latest 2.3.0 build with Venia sample data

## Tasks
- [ ] Discovery for continuously updated Vagrant container for PWA Studio environment 
- [ ] Review and summary of Vagrant findings and process
- [ ] Additional user stories/epics for implementation
- [ ] Example and demo (as appropriate)

**Comment by ericerway** [comment]
Related to #261 for Venia sample data.

**Comment by dmtrkad** [comment]
**Development**
Estmation: 4 SP
- [ ] 1, Vagrant R&D. Creating of the development environment 
- [ ] 2. Vagrant trough the Magento configuration 
- [ ] 3. Integrating of the PWA studia with Vagrant 
- [ ] 4. Sample data (Magenta or Venia ?) 

**Q&A:**
1. Venia sample data examples 
2. What's the outcome of this spike to reach the expectation?
3. Minimally supported versions of PHP, Magento. Configuration flow for new Vagrant files.

**Comment by ericerway** [comment]
We should definitely use Venia sample data. Goal here is to have a working Vagrant environment with instructions that can be used by others familiar with Vagrant in order to simplify setup and configuration. This needs to work on 2.3.0-beta and above. @zetlen will need to help with the location and configuration flow. Let's tag this for Sprint 27 next week.

**Comment by mhhansen** [comment]
@dmtrkad regarding `venia sample data`
in case it helps, checkout the devdocs
https://magento-research.github.io/pwa-studio/venia-pwa-concept/setup/

they were updated a few mins ago, now includes a script to get the venia sample data installed

**Comment by dmtrkad** [comment]
@sharkySharks Could you please comment on it ?

**Comment by sharkySharks** [comment]
rather than vagrant, I have made progress on getting a secure local dev environment running in docker in #734 . Will update all related issues once work is complete, starting work is in #682 .

**Comment by awilcoxa** [comment]
@sharkySharks are we still evaluating vagrant as an option? If not, let's go ahead and close this issue.
