### ISSUE TITLE
Implement Search auto-complete for Venia (PWA)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#313]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[X] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## Description

![image.png](https://images.zenhubusercontent.com/5a71f21a4b5806bc2bc51012/cbbf3476-c3aa-43da-bfda-c587be19d1cc)

As a shopper, I want to preview search results to help me browse products on the Venia storefront using basic keywords (e.g. hoodie) so that I can make an informed purchase.

Search for "Pants"
- Pants in Bottoms
- Pants in Sale and clearance
- Pants in Work Wear
- Pants in Casual Wear

#### Assumptions
- Product Suggestions will be considered in a future sprint; no ratings/reviews
- Results will continue to update with every keystroke; keyboard considerations
- Shopper directed to Results with selected phrase/category
- Gestures will be considered in the future (TBD)
 
## Tasks
- [ ] Discovery to understand realtime/cached product from API with keyboard
- [ ] Implement Search auto-complete with guidelines from UX/prototype
- [ ] Implement link from suggestion to Search Results
- [ ] Testing and documentation (https://github.com/magento-research/pwa-studio/wiki/Documentation-Guidelines)

**Comment by ericerway** [comment]
Kamino cloned this issue to [magento-research/pwa-studio](https://github.com/magento-research/pwa-studio/issues/350)

**Comment by ericerway** [comment]
Related to #264 with @Crifen and team.

**Comment by ericerway** [comment]
Kamino cloned this issue to [magento-research/pwa-studio](https://github.com/magento-research/pwa-studio/issues/372)
