### ISSUE TITLE
Implement My Account menu for Venia (PWA)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#351]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[X] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## Description

https://magento.invisionapp.com/d/main#/console/14921712/324119971/preview

![image](https://user-images.githubusercontent.com/2686596/46780264-fef3c600-cd1b-11e8-9098-d53b11ce8ddc.png)

As a shopper, I want to access profile, purchase, wish list and settings from Venia including sign out so that I can manage my account in the future.

- Customer name and email address
- Access to profile, purchase history and signout

#### Assumptions
- Dependent on account creation (competed)
- Rewards and points not part of MVP (concept only)
- Notifications not part of MVP (concept only)
- Update: Security Settings and Profile to be merged as "Account Settings"
 
## Tasks
- [x] Implement My Account (Account) menu with placeholder links and Sign Out (clear out token)
- [x] Implement links to profile (Account Settings) and purchase history (V1)
- [ ] Identify considerations for rewards, notifications, lists and settings (TBD)
- [ ] Testing and documentation (https://github.com/magento-research/pwa-studio/wiki/Documentation-Guidelines)

**Comment by ericerway** [comment]
Kamino cloned this issue to [magento-research/pwa-studio](https://github.com/magento-research/pwa-studio/issues/360)

**Comment by ericerway** [comment]
Assigning to @jimbo as a quick update to the navigation and menu work from Sprint 28.

**Comment by ericerway** [comment]
@Starotitorov let's start this ASAP as this is needed to link the new Purchase History work merged with #501. Remember we will *only* have items for Purchase History and Sign Out for the first release so let's keep this simple. Thanks!

**Comment by Starotitorov** [comment]
@ericerway Just to clarify, right now purchase history page will not be integrated to the application. We need to add support of client side routes to our venica-concept application first. Also, https://github.com/magento-research/pwa-studio/pull/501 contains only static markup for the story, we need to merge https://github.com/magento-research/pwa-studio/pull/439 with code related to data fetching on mocks for purchase history page.

**Comment by Starotitorov** [comment]
Pull request with the implementation and test https://github.com/magento-research/pwa-studio/pull/541
Pull request with the docs https://github.com/magento-research/pwa-studio/pull/542

**Comment by sirugh** [comment]
Additional related PRs: #570, #572

**Comment by sirugh** [comment]
I believe all we needed was purchase history and sign out links for this per @ericerway's comment from November. Further Account Menu work can be opened as a new issue.
