### ISSUE TITLE
Implement filtering for Category with Venia (PWA)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#361]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## Description

Zero state:
![image.png](https://images.zenhubusercontent.com/5a71f21a4b5806bc2bc51012/483a082b-4ec8-4a7c-b67c-1b2f2af034c4)

Expanded:
![image.png](https://images.zenhubusercontent.com/5a71f21a4b5806bc2bc51012/9f72886d-f8d9-4b9c-b425-1a10de341fe5)

Selected:
![image.png](https://images.zenhubusercontent.com/5a71f21a4b5806bc2bc51012/62cf536c-357e-4dd8-9ce4-743866c179ac)

As a shopper, I want to filter and sort products within a category so that I can make a purchase on Venia. These should be based programmatically based on sample Venia data.

Examples of filtering within Venia: (data)

- Fashion Material
- Fashion Style
- Fashion Color
- Price

#### Assumptions
- Dependent on Category page and ability to retrieve products by category
- Ratings not part of MVP (concept only)
- Utilizes SSR for filtering; related to sorting for Category #360(*)
- Minimize multiple queries (if possible); introspection on fashion/swatches (Venia data)
- UX for removal of filters is WIP; could be addressed in future
- Faceting needs should be identified and captured separately
- Utilize components (reuse) where possible

## Tasks
- [ ] Discovery for GraphQL based on #360 including URL reference (Sorting)
- [ ] Implement Filter By panel with basic options
- [ ] Testing and documentation (https://github.com/magento-research/pwa-studio/wiki/Documentation-Guidelines)

**Comment by ericerway** [comment]
Related to #360.

**Comment by ericerway** [comment]
Kamino cloned this issue to [magento-research/pwa-studio](https://github.com/magento-research/pwa-studio/issues/373)

**Comment by AlexeyKaryka** [comment]
Tasks for frontend

- [ ] Create component with filtering fields and buttons

- [ ] Create filter button on Category page, clicking this button should lead to Filter modal component

**Comment by AlexeyKaryka** [comment]
Am I right that layouts and content of all options besides Color aren't defined yet?

**Comment by AlexeyKaryka** [comment]
@soumya-ashok one more question: can I use design of "Size" section from product page in this Filter page?

**Comment by AlexeyKaryka** [comment]
@ericerway what do you mean by "Utilizes SSR for filtering;"? Is that about case when after clicking "Apply filters" url gets filter parameters and category page fetches data using those url query parameters?

**Comment by AlexeyKaryka** [comment]
Seems like magento doesn't have graphql endpoints for configurable options params, for instance "color", and they are stored only in items, so the only available case is to gather all items, and sent filtered colors, unfortunately this case will has too low performance and for me it's better to create new domen in graphql schema which will be charge of all configurable options params, so for example we will be able to fetch only all colors without looking in product items

**Comment by AlexeyKaryka** [comment]
branch with created components for filter button and filter modal: https://github.com/magento-research/pwa-studio/tree/feature/category-filter

**Comment by dmtrkad** [comment]
@zetlen , Could you please review Alexey's commit ?

**Comment by Starotitorov** [comment]
I created a pull request with changes made by Alexey https://github.com/magento-research/pwa-studio/pull/722

**Comment by soumya-ashok** [comment]
@AlexeyKaryka I have been on PTO, and just returned. I'v worked out a few options for the design of the rest the filtering sections besides color, but will need the team to provide feedback before I can share the finalized approach with you.

**Comment by awilcoxa** [comment]
@zetlen @jimbo issue/PR has been picked up by @codeAdrian but there's still the outstanding question that Alexey brought up about how to handle the gap of graphql endpoints. Can either of you weigh on on the topic w/ Adrian and figure out path forward?

**Comment by soumya-ashok** [comment]
https://magento.invisionapp.com/share/S2Q41VCR45C - Updated screens for filters

**Comment by codeAdrian** [comment]
@soumya-ashok , thank you for the updated designs.

@awilcoxa , can you assign me to this issue so I can easily keep track of it?

**Comment by cherdman** [comment]
Blocked by https://github.com/magento/graphql-ce/pull/259

**Comment by soumya-ashok** [comment]
On @codeAdrian 's comment on the related PR "It is a bit unclear how the "Apply filters", "Reset Filters" and clearing individual filters from checkboxes or active filters list should interact with URL. Should it update immediately or should user apply the changes by clicking "Apply filters"."

On a small mobile device, where the filters screen takes over the whole screen, there is no way for the shopper to know that filters are automatically being applied on selection, which is why the "Apply Filters" button exists, so they can specifically make the request once they are done selecting one or more filters.

However, we could automatically apply filters in the background on selection and have the "Apply Filters" button just close the modal, but that would make for odd UX in a desktop or larger mobile device context, if the shopper could see the filters being applied as they make selections.
