### ISSUE TITLE
Implement HTTP redirect for HTTPS (PWA)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#373]
## This issue is for the following packages:

[ ] `venia-concept`
[ ] `pwa-buildpack`
[X] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## Description

As a shopper, I want to be redirected to a secure version of Venia (HTTPS) if I visit an insecure version (HTTP) so that I can be confident my Venia purchase is secured.

This is a requirement for PWA per Google Lighthouse and applies to all of the Venia storefront.

#### Assumptions
- Dependent on examples of the Venia storefront (HTTPS)
 
## Tasks
- [ ] Discovery for HTTP/HTTPS redirect by environment, config and setup (UPWARD)
- [ ] Implement HTTPS redirect across Venia storefront; verify in Lighthouse
- [ ] Testing and documentation (https://github.com/magento-research/pwa-studio/wiki/Documentation-Guidelines)

**Comment by ericerway** [comment]
Kamino cloned this issue to [magento-research/pwa-studio](https://github.com/magento-research/pwa-studio/issues/374)

**Comment by ericerway** [comment]
No longer an issue; this is resolved on the server/UPWARD side. Closing for now.
