### ISSUE TITLE
Implement basic offline experience for Venia (PWA)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#374]
## This issue is for the following packages:

[ ] `venia-concept`
[ ] `pwa-buildpack`
[X] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## Description

As a shopper, I want basic feedback on the Venia storefront when my device is having connectivity issues or offline so that I know that I can have an uninterrupted shopping experience.

This is a requirement for PWA per Google Lighthouse and applies to all of the Venia storefront.

#### Assumptions
- Dependent on examples of the Venia storefront
- Dependent on 200 response type to respond
- Browser messaging for this scenario is not sufficient (must use service worker)
- Utilizes Workbox for basic behaviors/needs (service worker debugging in DevDocs; ref.)
 
## Tasks
- [ ] Discovery for offline response types (200) by Venia storefront and UPWARD
- [ ] Implement offline response (fallback); verify in Lighthouse
- [ ] Testing and documentation (https://github.com/magento-research/pwa-studio/wiki/Documentation-Guidelines)

**Comment by ericerway** [comment]
Marking as in progress from @pcvonz and team -- preview here: http://upward.bargreen.io

**Comment by pcvonz** [comment]
Some notes on the obstacles I've encountered so far. Let me know if anything sounds incorrect: 

**Problem:** Workbox will only cache `GET` requests. On the first load this works since Upward returns an html file. However, every subsequent load doesn't return an html file.

**Solution:** Cache requests in the `MagentoRouteHandler`. 

Recipe for how to access the cache in the [Workbox docs](https://developers.google.com/web/tools/workbox/guides/common-recipes#access_caches_from_your_web_apps_code).

<hr />

**Problem:** When components are retrieved through the `fetchRootComponent` method of `MagentoRouteHandler` and Venia has no network connection, this results in a failed network request. 

**Solution:** (slap dash, probably not what we want)

Bypass `MagentoRouteHandler` when offline and request the actual html file.

<hr />

[Related issue in the Workbox repo](https://github.com/GoogleChrome/workbox/issues/1620)

**Comment by rowan-m** [comment]
Great progress so far! Adding a few comments here on things I've seen. They may not all be relevant to this issue, but I wanted to make sure it's down.

1. As per the Lighthouse audit, the manifest is missing the 192px and 512px icons.
2. As per the Lighthouse audit, the manifest is missing a "`theme_color`"
3. Definitely happier with only trying to cache GET requests.
4. The manifest has a `.webmanifest` extension, which is fine but `.json` is more the convention. Sending the `content-type: application/json` header would be good though. I don't see any header currently.
5. Not sure about the `homescreen` entry in the upward config. Given that at least 3 icon sizes are needed, I feel like this is better served as static content.
6. *Enhancement:* Offline page should should be able to intelligently continue to the content once the connection is restored. This should be with a combination of listening for the `online` event and a configurable timeout (default to 30 sec) when the the request will be retried.
7. *Enhancement:* Ideally, the user should have some indication when they are being served offline content. This is tricky from a UX point of view because it's hard to tell the difference between just using the cache for a slow connection versus really being offline. A reasonable compromise is showing a persistent indicator (toast, banner, etc) when `navigator.onLine` is not `true`.
8. *Discussion:* Product pages probably need more sophisticated caching based on business, commercial, or even regulatory needs. Cache needs an expiry at the least. Should other aspects be changed when serving from cache - for example, showing the price?

**Comment by pcvonz** [comment]
Offline indicator demo:
Notification appears at the top of the page (not fixed). Once the user is online again it disappears and loads the page.
![online_offline_online](https://user-images.githubusercontent.com/6378569/48100897-f3d86c80-e1d9-11e8-805d-b0d767f0b670.gif)
