### ISSUE TITLE
Advanced Image optimization for Magento with UPWARD

### ISSUE THREAD

**Issue by awilcoxa** [magento-research/pwa-studio#398]
## This issue is for the following packages:

[ ] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[ ] Bug
[x ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

## Description

Today, Magento PWAs retrieve media assets (images, video, pdf, etc.) from Magento APIs (GraphQL/REST) with no optimization for file or image size. This creates performance issues on the display side for PWA. There are systems that exist for retrieval of resized/compressed images but they are not currently accessible to PWA due pre-existing dependencies and requirements. 

## Expected result:

A Magento Progressive Web App can retrieve compressed and/or resized images on demand in order to ensure best-in-class performance. This optimization should apply to the initial load of a PWA as well as throughout the entire customer journey/use. 

## Possible solutions:

Solutions that require discovery/investigation effort: 
1. Escalate requirement/need with API teams to ensure long-term scalable solution with single ownership. Risk: requires buy-in across functional teams for prioritization/delivery leading to slower velocity. 
2. Write middleware within UPWARD  to provide media optimization/resizing. Risk: potential throw away work that is redundant to existing services. Requires knowledge/experience with may not be readily available. 
3. Make a single purpose module. Risk: Large amount of effort and tech debt. 

Chosen solution: **2**. Write middleware within UPWARD.

### Tasks
- [ ] Add binary and JSON data handling to UPWARD file and data spec.
- [ ] Add resolvers for transformation.
- [ ] Add image compression to strategies and implement in upward-js.

**Comment by zetlen** [comment]
Related to #408: UPWARD needs to gain the concepts of binary data blobs and structured JSON as data to manipulate, as well as plain UTF-8 text.

**Comment by cherdman** [comment]
Resolved for the general case (https://github.com/magento-research/pwa-studio/pull/757)
