### ISSUE TITLE
Credit and debit payment experience for Venia (MVP)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#411]
From pwa-studio created by [ericerway](https://github.com/ericerway) : magento-research/pwa-studio#303  

## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## Description

As a shopper, I want to use a credit or debit card as a payment method on Venia so that I can complete my purchase online.

## Tasks
- [ ] Review Payment Methods in current M2 Admin for advanced/config details
- [ ] Design and prototype Visa, Mastercard, Discover, and Amex payment methods (guest)
- [ ] Review and incorporate feedback
- [ ] Update documentation (as appropriate)

**Comment by pcvonz** [comment]
I believe once #324 get's merged, implementing a fallback page will be a lot easier.

**Comment by ericerway** [comment]
Kamino cloned this issue to [magento-research/pwa-studio](https://github.com/magento-research/pwa-studio/issues/468)
