### ISSUE TITLE
Splash and loading experience for Venia (MVP)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#468]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## Description

As a shopper, I want to have a subtle experience on loading when I arrive at the Venia storefront (or new page) from a browser or app launched. This is a requirement for the Google Lighthouse PWA definition.

Two scenarios should be considered:
1. First load of Venia from app homescreen/doc (as a chromeless app or PWA)
2. First load of Venia pages (Product Details, etc.)

This can be one or two different experiences to address these scenarios. Additional information can be found on Google here: https://developers.google.com/web/fundamentals/web-app-manifest/#splash-screen

## Tasks
- [ ] Design and discovery for splash/loading page in Venia  
- [ ] Review and incorporate feedback
- [ ] Update documentation (as appropriate)
