### ISSUE TITLE
Accessibility improvements for Venia (Lighthouse)

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#594]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[X] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[ ] Bug
[X] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a shopper, I want to experience a fully accessible Venia storefront regardless of my abilities so that I can achieve WCAG 2.0 recommendations and Google Lighthouse recommendations.

https://www.w3.org/WAI/standards-guidelines/wcag/

## Expected result:

Updates to elements, colors, and language on key Venia experiences to improve accessibility as defined Google Lighthouse.

![image.png](https://images.zenhubusercontent.com/5a71f21a4b5806bc2bc51012/cdeea5a5-1adf-4099-8188-581547e6c1a2)

Categories: (affected)
- Elements Have Discernible Names
- Color Contrast is Satisfactory
- Page Specifies Valid Language

Pages: (affected)
- Homepage
- Category
- Product Details

## Tasks
- [ ] Update Venia home, category, and PD pages with recommended fixes from Lighthouse
- [ ] Review Google Lighthouse scores for Accessibility to verify (Lighthouse 4.0.0-alpha.1)
- [ ] Update documentation (as appropriate)

## Possible solutions:

Updates to Venia and UI components (peregrine) as appropriate.

**Comment by AlexeyKaryka** [comment]
@soumya-ashok could you please provide new color for the footer text? current one doesn't match contrast ration in the lighthouse

**Comment by ericerway** [comment]
Kamino cloned this issue to [magento-research/pwa-studio](https://github.com/magento-research/pwa-studio/issues/636)

**Comment by soumya-ashok** [comment]
@AlexeyKaryka Text color #707070 should satisfy the contrast requirement, please let me know if it doesn't.

**Comment by Starotitorov** [comment]
@soumya-ashok, yeah, this color satisfies the requirement, thank you.

**Comment by AlexeyKaryka** [comment]
@soumya-ashok could you please also provide new text color for the add-to-cart button?

**Comment by soumya-ashok** [comment]
Why do we need a new text color for the add to cart button? @AlexeyKaryka

**Comment by Starotitorov** [comment]
According to audit results, the color of the text does not satisfy color contrast requirement.

![add-to-cart-button](https://user-images.githubusercontent.com/11873143/49808999-dd8c7600-fd6e-11e8-8d6f-02338d5ebaf4.PNG)

**Comment by Starotitorov** [comment]
@soumya-ashok, I updated styles for 'Add to Cart' button. It seems that our colors combination for both buttons do not satisfy color contrast requirements. I still receive the same warning:

Background and foreground colors do not have a sufficient contrast ratio.

![add-to-cart](https://user-images.githubusercontent.com/11873143/49934079-755ca200-fede-11e8-8eeb-e7ad547a436a.PNG)

**Comment by soumya-ashok** [comment]
@Starotitorov I believe I already resolved this with @jimbo by increasing the size of the button text. Please follow his spec. Also, I just checked the contrast rating (screenshot attached) and it does pass - just not for small text.

<img width="740" alt="screen shot 2018-12-13 at 9 21 01 am" src="https://user-images.githubusercontent.com/25960021/49948162-809cd700-feb8-11e8-8c91-8456e09c7f6c.png">

**Comment by dmtrkad** [comment]
@ericerway , Do we need to close this one as implemented ?
